In [2]:
import cv2
import numpy as np

In [3]:
img = np.zeros((8,8),dtype=np.uint8)
print("img=\n",img)
cv2.imshow("one",img)
print("[0,3]",img[0,3])
img[0,3] =255
print("修改后img = \n",img)
cv2.imshow("two",img)
cv2.waitKey()
cv2.destroyAllWindows()


img=
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[0,3] 0
修改后img = 
 [[  0   0   0 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]


In [8]:
img = cv2.imread('../test.jpg')
cv2.imshow('before',img)
for i in range(10,100):
    for j in range(80,100):
        img[i,j] = [0,255,255]
print(img[10,10])
cv2.imshow('after',img)
cv2.waitKey()
cv2.destroyAllWindows()

[147 163 180]


In [10]:
arr = np.zeros((300,300,3),dtype = np.uint8)
arr[:,0:100,0] = 255
arr[:,100:200,1] = 255
arr[:,200:300,2] = 255
cv2.imshow('img',arr)
cv2 .waitKey()
cv2.destroyAllWindows()

In [13]:
arr = np.random.randint(10,99,size=[300,300],dtype=np.uint8)
cv2.imshow("before",arr)
arr.itemset((3,2),255)
cv2.imshow("after",arr)
cv2 .waitKey()
cv2.destroyAllWindows()
